syntax = "proto3";

package TextSmith;

message Recent {
    string title = 1;
    string path = 2;
}

message Prefs {
    repeated string actingScrips = 1;
    bool autoSave = 2;
    uint64 autoSaveInterval = 3;
    bool binary = 4;
    string bold = 5;
    string chapterTag = 6;
    string coverTag = 7;
    string fontFamily = 8;
    int32 fontSIze = 9;
    string footer = 10;
    string header = 11;
    string italic = 12;
    repeated uint64 mainSplitter = 13;
    double marginBottom = 14;
    double marginLeft = 15;
    double marginRight = 16;
    double marginTop = 17;
    repeated uint64 otherSplitter = 18;
    int32 orientation = 19;
    string pageSize = 20;
    int64 position = 21;
    repeated Recent recentNovels = 22;
    string sceneTag = 23;
    string separator = 24;
    int32 theme = 25;
    bool toolbarVisible = 26;
    bool typingSounds = 27;
    string uiFontFamily = 28;
    int32 uiFontSize = 29;
    string underline = 30;
    bool useSeparator = 31;
    int32 voice = 32;
    repeated int32 window = 33;
    map<string, string> vars = 34;
}

message Image {
    string url = 1;
    repeated uint32 data = 2;
}

message Extra {
    Prefs prefs = 1;
    int64 currentNode = 2;
    int64 position = 3;
    map<int64, bool> state = 4;
    repeated Image images = 5;
    repeated string words = 6;
}

message BlockFormat {
    int64 alignment = 1;
    int64 indent = 2;
}

message TextCharFormat {
    bool bold = 1;
    bool italic = 2;
    bool underline = 3;
}

message TextFormat {
    TextCharFormat charFormat = 1;
    string text = 2;
}

message TextImageFormat {
    string name = 1;
    int64 width = 2;
    int64 height = 3;
}

message TextFragment {
    oneof is {
        TextImageFormat imageFormat = 1;
        TextFormat textFormat = 2;
    }
}

message Block {
    BlockFormat format = 1;
    TextCharFormat charFormat = 2;
    repeated TextFragment fragments = 3;
}

message TextDocument {
    repeated Block blocks = 1;
}

message Item {
    TextDocument doc = 1;
    uint64 id = 2;
    string name = 3;
    int64 position = 4;
    repeated string tags = 5;
}

message TreeNode {
    int64 id = 1;
    repeated TreeNode branches = 2;
}

message Branches {
    repeated TreeNode treeNode = 1;
}

message Novel {
    string filename = 1;
    Extra extra = 2;
    int64 root = 3;
    repeated Item items = 4;
    Branches branches = 5;
}